"""
EventFlow AI — Runtime Cascade Predictor (Step 3C)

At API request time, this module:
  1. Loads the pre-computed junction co-occurrence matrix (cascade_matrix.json)
     that was generated by the ML pipeline's cascade_analyzer.py.
  2. Computes a real-time cascade_probability for the incoming event, using
     the same weighted formula used during training.
  3. Returns a CascadeResult object that feeds into:
       - The Duration model (as a feature → reduces MAE on long-tail events)
       - The API prediction response (as human-readable risk info)

The cascade probability explains WHY some events take 4+ hours to resolve —
they trigger secondary incidents at nearby junctions.
"""

import json
import math
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from app.config import settings


# ────────────────────────────────────────────────────
# Constants (must mirror cascade_analyzer.py)
# ────────────────────────────────────────────────────
CASCADE_WINDOW_MINUTES = 60
CASCADE_RADIUS_KM      = 5.0
MIN_CO_OCCURRENCES     = 2
DEFAULT_CASCADE_PROB   = 0.05

HIGH_CASCADE_CAUSES = {
    "accident", "public_event", "procession", "vip_movement",
    "protest", "construction", "congestion",
}
LOW_CASCADE_CAUSES = {
    "vehicle_breakdown", "pot_holes", "debris",
    "fog_low_visibility", "water_logging",
}

# Fallback cause-level cascade rates (derived from Bengaluru dataset)
# Used when cascade_matrix.json has not been generated yet.
FALLBACK_CAUSE_RATES: Dict[str, float] = {
    "vip_movement":      0.72,
    "public_event":      0.61,
    "protest":           0.57,
    "procession":        0.53,
    "accident":          0.48,
    "construction":      0.41,
    "congestion":        0.38,
    "tree_fall":         0.29,
    "water_logging":     0.22,
    "road_conditions":   0.18,
    "others":            0.15,
    "debris":            0.12,
    "vehicle_breakdown": 0.10,
    "pot_holes":         0.08,
    "fog_low_visibility":0.07,
}

# Bengaluru junction coordinates (same as diversion_engine.py)
JUNCTION_COORDS: Dict[str, tuple] = {
    "MekhriCircle":        (13.0065, 77.5800),
    "HebbalFlyover":       (13.0358, 77.5970),
    "SilkBoard":           (12.9170, 77.6230),
    "TinFactory":          (13.0060, 77.6390),
    "YeshwanthpuraCircle": (13.0270, 77.5450),
    "MajesticBusStand":    (12.9770, 77.5720),
    "KRPuram":             (13.0010, 77.6810),
    "MarathahalliBridge":  (12.9560, 77.7010),
    "Koramangala":         (12.9350, 77.6250),
    "Whitefield":          (12.9700, 77.7500),
    "ElectronicCity":      (12.8450, 77.6600),
    "Yelahanka":           (13.1000, 77.5940),
    "Jayanagar":           (12.9250, 77.5830),
    "Malleshwaram":        (13.0030, 77.5680),
    "Indiranagar":         (12.9720, 77.6410),
    "BTM":                 (12.9160, 77.6100),
    "HSRLayout":           (12.9120, 77.6500),
    "BannerghattaRoad":    (12.8900, 77.5990),
    "JPNagar":             (12.9060, 77.5860),
    "BasavanagudiCircle":  (12.9430, 77.5740),
    "MysoreRoadJunc":      (12.9570, 77.5440),
    "TumkurRoadJunc":      (13.0310, 77.5370),
    "SilkBoardFlyover":    (12.9165, 77.6220),
    "ChinnaswamyStadium":  (12.9789, 77.5995),
    "CubbonPark":          (12.9763, 77.5929),
    "MGRoad":              (12.9735, 77.6076),
    "RichmondCircle":      (12.9670, 77.6090),
    "LalbaghGate":         (12.9520, 77.5850),
    "VidhanaSoudha":       (12.9795, 77.5912),
    "PalaceGround":        (12.9950, 77.5780),
    "KanteeravStadium":    (12.9750, 77.5930),
}


# ────────────────────────────────────────────────────
# Data class for structured cascade result
# ────────────────────────────────────────────────────
@dataclass
class CascadeResult:
    cascade_probability: float            # Core ML feature [0, 1]
    risk_level: str                       # "Low" | "Medium" | "High" | "Critical"
    likely_affected_junctions: List[str]  # Top-N junctions at risk
    duration_multiplier: float            # How much duration may stretch
    explanation: str                      # Human-readable reason


# ────────────────────────────────────────────────────
# Main Cascade Predictor class
# ────────────────────────────────────────────────────
class CascadePredictor:
    """
    Runtime cascade predictor. Loads the junction co-occurrence matrix
    once at startup and computes cascade scores at prediction time.
    """

    def __init__(self):
        self._matrix: Optional[Dict] = None
        self._pair_rates: Dict[str, float] = {}
        self._cause_rates: Dict[str, float] = {}
        self._junction_max_rate: Dict[str, float] = {}
        self._loaded = False

    def load_matrix(self, matrix_path: Optional[str] = None) -> bool:
        """
        Load the cascade_matrix.json generated by the ML pipeline.
        Falls back to hardcoded rates if the file doesn't exist yet
        (e.g., before first model training run).
        """
        if matrix_path is None:
            # Default path: ../ml/data/processed/cascade_matrix.json
            models_dir = getattr(settings, "MODELS_DIR",
                                 os.path.join(os.path.dirname(__file__),
                                              "..", "..", "..", "ml", "models"))
            base = os.path.dirname(models_dir)
            matrix_path = os.path.join(base, "ml", "data",
                                       "processed", "cascade_matrix.json")

        if os.path.exists(matrix_path):
            try:
                with open(matrix_path, "r", encoding="utf-8") as f:
                    self._matrix = json.load(f)
                self._pair_rates  = self._matrix.get("pair_rates", {})
                self._cause_rates = self._matrix.get("cause_cascade_rates", {})
                self._build_junction_max_rates()
                self._loaded = True
                print(f"[CascadePredictor] Matrix loaded from {matrix_path} "
                      f"({len(self._pair_rates)} pairs)")
                return True
            except Exception as exc:
                print(f"[CascadePredictor] Failed to load matrix: {exc}")

        # Graceful fallback to hardcoded rates
        print("[CascadePredictor] Using fallback cause rates "
              "(run ML pipeline to generate full matrix)")
        self._cause_rates = FALLBACK_CAUSE_RATES.copy()
        self._loaded = False
        return False

    def _build_junction_max_rates(self):
        """Pre-index the best cascade rate per origin junction."""
        from collections import defaultdict
        junc_max: Dict[str, float] = defaultdict(float)
        pair_counts = self._matrix.get("pair_counts", {}) if self._matrix else {}
        for pair_key, rate in self._pair_rates.items():
            count = pair_counts.get(pair_key, 0)
            if count >= MIN_CO_OCCURRENCES:
                junc_a = pair_key.split("||")[0]
                junc_max[junc_a] = max(junc_max[junc_a], rate)
        self._junction_max_rate = dict(junc_max)

    # ─────────────────────────────────────────────────
    # Core prediction method
    # ─────────────────────────────────────────────────
    def predict_cascade(
        self,
        event_cause:  str,
        junction:     str,
        latitude:     float,
        longitude:    float,
        hour_ist:     int,
        priority:     str = "Low",
        is_peak:      bool = False,
    ) -> CascadeResult:
        """
        Compute cascade probability for a live event.

        Returns a CascadeResult with:
          - cascade_probability → float [0,1]  (injected into duration model)
          - risk_level          → string label
          - likely_affected_junctions → list of nearby at-risk junctions
          - duration_multiplier → estimated stretch on resolution time
          - explanation         → human-readable text for the dashboard
        """
        cause = event_cause.lower().strip()

        # ── Component 1: Cause-level historical rate ──
        cause_rate = self._cause_rates.get(cause,
                     FALLBACK_CAUSE_RATES.get(cause, DEFAULT_CASCADE_PROB))

        # ── Component 2: Junction-specific rate ───────
        junc_rate = self._junction_max_rate.get(junction, DEFAULT_CASCADE_PROB)

        # ── Component 3: Peak-hour bonus ──────────────
        is_peak_hour = is_peak or (7 <= hour_ist <= 10 or 17 <= hour_ist <= 21)
        peak_bonus   = 0.08 if is_peak_hour else 0.0

        # ── Component 4: Priority bonus ───────────────
        priority_bonus = 0.05 if priority == "High" else 0.0

        # ── Component 5: Cause-type category offset ───
        if cause in HIGH_CASCADE_CAUSES:
            type_bonus = 0.06
        elif cause in LOW_CASCADE_CAUSES:
            type_bonus = -0.04
        else:
            type_bonus = 0.0

        # ── Weighted combination ──────────────────────
        cascade_prob = (
            0.40 * cause_rate
            + 0.35 * junc_rate
            + peak_bonus
            + priority_bonus
            + type_bonus
        )
        cascade_prob = round(max(0.0, min(1.0, cascade_prob)), 4)

        # ── Risk label ────────────────────────────────
        if cascade_prob < 0.20:
            risk_level = "Low"
        elif cascade_prob < 0.40:
            risk_level = "Medium"
        elif cascade_prob < 0.65:
            risk_level = "High"
        else:
            risk_level = "Critical"

        # ── Find likely affected junctions ────────────
        affected = self._find_at_risk_junctions(
            lat=latitude, lon=longitude,
            origin_junction=junction,
            cascade_prob=cascade_prob
        )

        # ── Duration multiplier ───────────────────────
        # A cascade event takes proportionally longer to clear
        # (derived from analysis: each 0.1 prob ≈ +12% duration)
        duration_multiplier = round(1.0 + cascade_prob * 1.2, 2)

        # ── Human-readable explanation ─────────────────
        explanation = self._build_explanation(
            cause, junction, cascade_prob, risk_level,
            affected, is_peak_hour, duration_multiplier
        )

        return CascadeResult(
            cascade_probability=cascade_prob,
            risk_level=risk_level,
            likely_affected_junctions=affected,
            duration_multiplier=duration_multiplier,
            explanation=explanation,
        )

    def _find_at_risk_junctions(
        self,
        lat: float,
        lon: float,
        origin_junction: str,
        cascade_prob: float,
        top_n: int = 3,
    ) -> List[str]:
        """
        Return top-N junctions within CASCADE_RADIUS_KM that are
        historically correlated with the origin junction.
        Falls back to nearest junctions by distance.
        """
        candidates = []

        # If we have pair data, prefer historically correlated junctions
        if self._matrix:
            pair_counts = self._matrix.get("pair_counts", {})
            for pair_key, count in pair_counts.items():
                junc_a, junc_b = pair_key.split("||")
                if junc_a == origin_junction and count >= MIN_CO_OCCURRENCES:
                    rate = self._pair_rates.get(pair_key, 0)
                    candidates.append((junc_b, rate, count))
            candidates.sort(key=lambda x: -x[1])
            if candidates:
                return [c[0] for c in candidates[:top_n]]

        # Fallback: nearest junctions by haversine distance
        distances = []
        for jname, (jlat, jlon) in JUNCTION_COORDS.items():
            if jname == origin_junction:
                continue
            dist = self._haversine(lat, lon, jlat, jlon)
            if dist <= CASCADE_RADIUS_KM:
                distances.append((jname, dist))
        distances.sort(key=lambda x: x[1])
        return [d[0] for d in distances[:top_n]]

    @staticmethod
    def _build_explanation(
        cause: str,
        junction: str,
        prob: float,
        risk_level: str,
        affected_junctions: List[str],
        is_peak: bool,
        duration_mult: float,
    ) -> str:
        parts = []
        parts.append(
            f"A '{cause}' event at '{junction}' has a {prob:.0%} cascade risk "
            f"(Risk Level: {risk_level})."
        )
        if is_peak:
            parts.append("Peak-hour conditions increase secondary incident likelihood.")
        if affected_junctions:
            junc_list = ", ".join(affected_junctions)
            parts.append(
                f"Historically correlated junctions that may be affected: {junc_list}."
            )
        parts.append(
            f"Estimated resolution time may be {duration_mult:.1f}× the baseline "
            f"duration due to cascade effects."
        )
        return " ".join(parts)

    @staticmethod
    def _haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        R = 6371.0
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = (math.sin(dlat / 2) ** 2
             + math.cos(math.radians(lat1))
             * math.cos(math.radians(lat2))
             * math.sin(dlon / 2) ** 2)
        return R * 2 * math.asin(math.sqrt(max(0.0, a)))


# ────────────────────────────────────────────────────
# Singleton instance — loaded once at application start
# ────────────────────────────────────────────────────
cascade_predictor = CascadePredictor()
